# This workflow builds and uploads development python artifacts

name: Build and Publish Python Development Package
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      python-version:
        required: false
        type: string
        default: 3.12
    secrets:
      github-token:
        required: true
      pypi-token:
        required: true

jobs:
  development-package:
    permissions:
      contents: write
      id-token: write
      actions: write
    uses: irvingleonard/reusable-workflows/.github/workflows/python-build-publish-package.yml@v1
    with:
      package-name: ${{ inputs.package-name }}
      python-version: ${{ inputs.python-version }}
      tag-regex: ^v[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+$
      stable-version: false
      env-name: Development
    secrets:
      github-token: ${{ secrets.github-token }}
      pypi-token: ${{ secrets.pypi-token }}
