name: Build and Publish Python Package
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      python-version:
        required: true
        type: string
      tag-regex:
        required: true
        type: string
      stable-version:
        required: true
        type: boolean
      env-name:
        required: true
        type: string
    secrets:
      github-token:
        required: true
      pypi-token:
        required: true

jobs:
  python-package-get-version:
    uses: irvingleonard/reusable-workflows/.github/workflows/python-package-get-version.yml@v1
    with:
      package-name: ${{ inputs.package-name }}
      python-version: ${{ inputs.python-version }}

  create-tag:
    runs-on: ubuntu-latest
    needs: python-package-get-version
    permissions:
      actions: write
      contents: write
      id-token: write
    environment: ${{ inputs.env-name}}
    steps:
      - name: Check if Tag is Valid
        id: check-tag
        run: |
          if [[ ! ${{ needs.python-package-get-version.outputs.package_version }} =~ ${{ inputs.tag-regex }} ]]; then
            echo "Version found: ${{ needs.python-package-get-version.outputs.package_version }} is not a valid value for this environment"
            else 
            echo "Version found: ${{ needs.python-package-get-version.outputs.package_version }} is a valid value for this environment"
            echo "VALID_VERSION=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Tag
        id: create-tag
        if: steps.check-tag.outputs.VALID_VERSION == true
        continue-on-error: true
        env:
          TAG: ${{ needs.python-package-get-version.outputs.package_version  }}
        run: |
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}

      - name: Get Release for Tag
        if: steps.check-tag.outputs.VALID_VERSION == true
        id: get_release
        uses: irvingleonard/github-action-git-get-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        with:
          tag: ${{ needs.python-package-get-version.outputs.package_version }}
          doNotFailIfNotFound: true

    outputs:
      valid_version: ${{ steps.check-tag.outputs.VALID_VERSION }}
      tag: ${{ needs.python-package-get-version.outputs.package_version }}
      release_found: ${{ steps.get_release.outputs.id }}

  build-n-publish:
    needs: create-tag
    if: needs.create-tag.outputs.release_found == null && needs.create-tag.outputs.valid_version == 'true'
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    environment: ${{ inputs.env-name}}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Devautotools
        run: |
          python3 -m venv venv_devautotools
          ./venv_devautotools/bin/pip install --upgrade pip
          ./venv_devautotools/bin/pip install --upgrade devautotools

      - name: Deploy Local Virtual Environment
        run: |
          ./venv_devautotools/bin/python -m devautotools deploy_local_venv

      - name: Install Test Coverage Python Modules
        run: |
          ./venv/bin/pip install --upgrade coverage

      - name: Install Build Module
        run: |
          ./venv/bin/pip install --upgrade build

      - name: Build Package
        run: |
          ./venv/bin/python3 -m build --no-isolation

      - name: Create Github Pre-Release
        if: inputs.stable-version != true
        id: create_release
        uses: irvingleonard/github-action-create-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag }}
          files: dist/*
          prerelease: true

      - name: Create Github Release
        if: inputs.stable-version == true
        id: create_release
        uses: irvingleonard/github-action-create-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag }}
          files: dist/*

      - name: Publish package distributions to TestPyPI
        if: inputs.stable-version != true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.pypi-token }}

      - name: Publish package distributions to PyPI
        if: inputs.stable-version == true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi-token }}