# Workflow to get the version of a python package

name: Validate Python Package
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      python-version:
        required: false
        type: string
        default: 3.12
    outputs:
      package_version:
        description: "The version reported by the package"
        value: ${{ jobs.python_package_get_version.outputs.package_version }}

jobs:
  python_package_get_version:
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.get_package_version.outputs.PACKAGE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Devautotools
        run: |
          python3 -m venv venv_devautotools
          ./venv_devautotools/bin/pip install --upgrade pip
          ./venv_devautotools/bin/pip install --upgrade devautotools

      - name: Deploy Local Virtual Environment
        run: |
          ./venv_devautotools/bin/python -m devautotools deploy_local_venv

      - name: Get Python Package Version
        id: get_package_version
        run: |
          echo "PACKAGE_VERSION=v"`./venv/bin/python3 -m ${{ inputs.package-name }} --version` >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT