# This workflow builds and uploads stable python artifacts

name: Build and Publish Python Stable Package
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      python-version:
        required: false
        type: string
        default: 3.12
      env-name:
        required: false
        type: string
        default: Production
    secrets:
      github-token:
        required: true

jobs:
  stable-package:
    permissions:
      contents: write
      id-token: write
      actions: write
    uses: irvingleonard/reusable-workflows/.github/workflows/python-build-publish-package.yml@v1
    with:
      package-name: ${{ inputs.package-name }}
      python-version: ${{ inputs.python-version }}
      tag-regex: ^v[0-9]+\.[0-9]+\.[0-9]+(\.post[0-9]+)?$
      stable-version: true
      env-name: ${{ inputs.env-name }}
    secrets:
      github-token: ${{ secrets.github-token }}
