# This workflow builds and uploads python artifacts

name: Build and Publish Python Stable Package
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
    secrets:
      token:
        required: true
      pypi_token:
        required: true

jobs:
  stable-package:
    permissions:
      contents: write
      id-token: write
      actions: write
    uses: irvingleonard/reusable-workflows/.github/workflows/python-build-publish-package.yml@v0.0.10
    with:
      package-name: ${{ inputs.package-name }}
      python-version: 3.12
      tag-regex: ^v[0-9]+\.[0-9]+\.[0-9]+(\.post[0-9]+)?$
      stable-version: true
      env-name: Production
    secrets:
      token: ${{ secrets.token }}
      pypi_token: ${{ secrets.pypi_token }}
