# This workflow builds and uploads python artifacts

name: Build and Publish Python Development Package
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
    secrets:
      token:
        required: true
      pypi_token:
        required: true

env:
  ENV_NAME: Development
  PYTHON_VERSION: 3.12
  TAG_REGEX: ^v[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+$
  TEST_PYPI_URL: https://test.pypi.org/legacy/

jobs:
  build-package:
    permissions:
      contents: write
      id-token: write
      actions: write
    uses: irvingleonard/reusable-workflows/.github/workflows/python-build-publish-package.yml@v0.0.1
    with:
      package-name: ${{ inputs.package-name }}
      python-version: ${{ env.PYTHON_VERSION }}
      tag-regex: ${{ env.TAG_REGEX }}
      stable-version: false
      env-name: ${{ env.ENV_NAME }}
      pypi-url: ${{ env.TEST_PYPI_URL }}
    secrets:
      token: ${{ secrets.token }}
      pypi_token: ${{ secrets.pypi_token }}
