# Workflow to validate python packages

name: Validate Python package
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      python-version:
        required: false
        type: string
        default: 3.12
    secrets:
      github-token:
        required: true

env:
  ALL_VALID_TAGS_REGEX: ^v[0-9]+\.[0-9]+\.[0-9]+(\.(dev|post)[0-9]+)?$
  STATUS_CHECK_NAME: Valid Python package

jobs:
  validate-python-package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Provision Virtual Environment (including updated pip and dependencies)
        run: |
          python3 -m pip install devautotools
          python3 -m devautotools deploy_local_venv
          ./venv/bin/pip install --upgrade coverage

      - name: Get Python Package Version
        id: get_package_version
        run: |
          echo "PACKAGE_VERSION=v"`./venv/bin/python3 -m ${{ inputs.package-name }} --version` >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Check if Version is Valid
        id: check_version
        run: |
          if [[ ! ${{ steps.get_package_version.outputs.PACKAGE_VERSION }} =~ ${{ env.ALL_VALID_TAGS_REGEX }} ]]; then
            echo "INVALID_TAG=True" >> $GITHUB_OUTPUT
            echo "Version found: ${{ steps.get_package_version.outputs.PACKAGE_VERSION }} is not a valid semver version number";
          else 
            echo "Version found: ${{ steps.get_package_version.outputs.PACKAGE_VERSION }} is a valid semver version number"
          fi

      - name: Set Failure Status for Invalid Version
        if: steps.check_version.outputs.INVALID_TAG != null
        uses: irvingleonard/github-actions-set-commit-status@master
        with:
          token: ${{ secrets.github-token }}
          status: "failure"
          context: ${{ env.STATUS_CHECK_NAME}}
          description: "Invalid Version: ${{ steps.get_package_version.outputs.PACKAGE_VERSION }}"

      - name: Exit if Version is Invalid
        if: steps.check_version.outputs.INVALID_TAG != null
        run: exit 1

      - name: Get Release for Version (Tag)
        if: steps.get_package_version.outputs.PACKAGE_VERSION
        id: get_release
        uses: irvingleonard/github-action-git-get-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        with:
          tag: ${{ steps.get_package_version.outputs.PACKAGE_VERSION }}
          doNotFailIfNotFound: true

      - name: Set Failure Status for Release Already Found
        if: steps.get_release.outputs.id != null
        uses: irvingleonard/github-actions-set-commit-status@master
        with:
          token: ${{ secrets.github-token }}
          status: "failure"
          context: ${{ env.STATUS_CHECK_NAME }}
          description: "Release already created for ${{ steps.get_package_version.outputs.PACKAGE_VERSION }}"

      - name: Exit if Release Already Found
        if: steps.get_release.outputs.id != null
        run: exit 1

      - name: Run Tests
        id: tests
        run: ./venv/bin/coverage run -m unittest discover -v -s ${{ vars.TESTS_FOLDER || 'tests' }} && echo "TESTS_RESULT=passing" >> "$GITHUB_OUTPUT"
        continue-on-error: true

      - name: Set Failure Status for Tests
        if: steps.tests.outputs.TESTS_RESULT != 'passing'
        uses: irvingleonard/github-actions-set-commit-status@master
        with:
          token: ${{ secrets.github-token }}
          status: "failure"
          description: "Tests failing: ${{steps.tests.outputs.FAILED_TESTS}}"
          context: ${{ env.STATUS_CHECK_NAME }}

      - name: Exit if Tests Failed
        if: steps.tests.outputs.TESTS_RESULT != 'passing'
        run: exit 1

      - name: Create success status
        uses: irvingleonard/github-actions-set-commit-status@master
        with:
          token: ${{ secrets.github-token }}
          status: "success"
          context: ${{ env.STATUS_CHECK_NAME }}